name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build push trino
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ttbb/trino:nake
          platforms: linux/amd64,linux/arm64
      - name: Save Docker Images
        run: docker pull ttbb/trino:nake;docker save ttbb/trino:nake -o trino-nake.tar.gz
      - uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: latest_docker_image
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest_docker_image
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Latest docker image"
          draft: false
          name: "latest docker image"
          tag_name: latest_docker_image
          files: trino-nake.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
